title:              Minj0i Blog
email:              h_hoh@naver.com
description:        Minj0i Git Blog
author:             MinJeong Kim
baseurl:            "/blog"
url:                "https://minj0i.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
 
remote_theme : StartBootstrap/startbootstrap-clean-blog-jekyll
